#!/usr/bin/env node
// First-run installer: npm install, admin account creation, schema, .env, and install lock.
import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline/promises';
import { spawnSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { randomTokenHex, hashPassword } from './src/util/crypto.js';
import { openDatabase, runMigrations } from './src/store/db.js';
import { loadEnvFile } from './src/util/config.js';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const MIN_NODE = { major: 22, minor: 13 };

// Validates an admin email address.
export function validateEmail(value) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(value || '').trim());
}

// Validates an admin password against the minimum length policy.
export function validatePassword(value, minLength = 10) {
  return typeof value === 'string' && value.length >= minLength;
}

// Returns true when the running Node version can provide node:sqlite.
function nodeSupported(version) {
  const [major, minor] = String(version).split('.').map(Number);
  return major > MIN_NODE.major || (major === MIN_NODE.major && minor >= MIN_NODE.minor);
}

// Reads a line from the terminal without echoing the typed characters.
function askHidden(question) {
  process.stdout.write(question);
  return new Promise((resolve, reject) => {
    const stdin = process.stdin;
    const wasRaw = stdin.isRaw;
    stdin.setRawMode?.(true);
    stdin.resume();
    let value = '';
    // Handles one keystroke at a time for masked input.
    function onData(chunk) {
      const text = chunk.toString('utf8');
      for (const char of text) {
        if (char === '\r' || char === '\n') {
          cleanup();
          process.stdout.write('\n');
          resolve(value);
          return;
        }
        if (char === '\u0003') {
          cleanup();
          process.stdout.write('\n');
          reject(new Error('Aborted'));
          return;
        }
        if (char === '\u007f' || char === '\b') {
          value = value.slice(0, -1);
          continue;
        }
        value += char;
      }
    }
    // Restores terminal state and removes listeners.
    function cleanup() {
      stdin.removeListener('data', onData);
      stdin.setRawMode?.(wasRaw ?? false);
      stdin.pause();
    }
    stdin.on('data', onData);
  });
}

// Runs the interactive setup flow: npm install, prompts, schema, admin, lock.
export async function main() {
  loadEnvFile(path.join(ROOT, '.env'));
  const storagePath = path.resolve(process.env.STORAGE_PATH || path.join(ROOT, 'storage'));
  const dbPath = path.resolve(process.env.DB_PATH || path.join(storagePath, 'gateway.db'));
  const lockPath = path.join(storagePath, 'install.lock');

  console.log('SmolOrchestrator setup');
  console.log('=======================');
  if (fs.existsSync(lockPath)) {
    console.log(`Already installed (${lockPath} exists).`);
    console.log('To reinstall, remove the lock file and database manually.');
    return;
  }
  if (!nodeSupported(process.versions.node)) {
    throw new Error(`Node.js >= ${MIN_NODE.major}.${MIN_NODE.minor} is required (found ${process.versions.node})`);
  }

  const npmCommand = process.platform === 'win32' ? 'npm.cmd' : 'npm';
  console.log('\nRunning npm install...');
  const install = spawnSync(npmCommand, ['install', '--no-audit', '--no-fund'], {
    stdio: 'inherit',
    shell: process.platform === 'win32',
    cwd: ROOT,
  });
  if (install.status !== 0) throw new Error('npm install failed');

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  try {
    let email = '';
    for (;;) {
      email = (await rl.question('\nAdmin email: ')).trim();
      if (validateEmail(email)) break;
      console.log('Enter a valid email address.');
    }
    const minLength = Number(process.env.MIN_PASSWORD_LENGTH || 10);
    let password = '';
    for (;;) {
      password = await askHidden('Admin password (input hidden): ');
      if (!validatePassword(password, minLength)) {
        console.log(`Password must be at least ${minLength} characters.`);
        continue;
      }
      const confirmation = await askHidden('Confirm password: ');
      if (confirmation === password) break;
      console.log('Passwords do not match.');
    }
    const httpsAnswer = (await rl.question('Serve this instance over HTTPS? [Y/n]: ')).trim().toLowerCase();
    const secureCookie = httpsAnswer === '' || httpsAnswer.startsWith('y');

    fs.mkdirSync(storagePath, { recursive: true });
    const envPath = path.join(ROOT, '.env');
    const envBody = [
      `# Generated by setup.js on ${new Date().toISOString()}.`,
      '# See .env.example for all supported variables.',
      'HOST=127.0.0.1',
      'PORT=8787',
      `STORAGE_PATH=${storagePath.replace(/\\/g, '/')}`,
      `APP_SECRET=${randomTokenHex(32)}`,
      `COOKIE_SECURE=${secureCookie ? 'true' : 'false'}`,
      '',
    ].join('\n');
    fs.writeFileSync(envPath, envBody, { mode: 0o600 });
    try {
      fs.chmodSync(envPath, 0o600);
    } catch {
      // Windows may not support POSIX modes; the file remains user-scoped.
    }

    const db = openDatabase(dbPath);
    try {
      const applied = runMigrations(db, path.join(ROOT, 'migrations'), null);
      db.prepare('INSERT INTO admin (email, password_hash, created_at) VALUES (?, ?, ?)')
        .run(email, hashPassword(password), Date.now());
      fs.writeFileSync(lockPath, new Date().toISOString(), { mode: 0o600 });
      console.log(`\nSetup complete. ${applied} migration(s) applied.`);
      console.log(`Admin account: ${email}`);
      console.log('Start the gateway with: npm start');
    } finally {
      db.close();
    }
  } finally {
    rl.close();
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(`\nSetup failed: ${error.message}`);
    process.exit(1);
  });
}
